name: Docker Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}

      - name: Login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup docker build
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-actions@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/epic-free-games-bot:latest